apiVersion: apps/v1
kind: Deployment
metadata:
  name: system-news-deployment
spec:
  replicas: 1
  template:
    metadata:
      name: system-news
      labels:
        app: system-news
    spec:
      containers:
        - name: system-news-container
          image: aluracursos/sistema-noticias:1
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: system-configmap
  selector:
    matchLabels:
      app: system-news