apiVersion: v1
kind: Pod
metadata:
  name: pod-sc
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      volumeMounts:
        - mountPath: /data
          name: first-pv
  volumes:
    - name: first-pv
      persistentVolumeClaim:
        claimName: pvc-2